version: '3.7'
services:
  db:       
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password        
    environment:
      MYSQL_ROOT_PASSWORD: 87ti5ox6
      MYSQL_DATABASE: lumisportal
      MYSQL_USER:  lumisportal
      MYSQL_PASSWORD: lumisportal
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306 
    networks: 
      - lumis
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
    
  elasticsearch:    
    #build: ./elasticsearch
    image: jeduoliveira/lumisportal-stack-elasticsearch:6.6.2    
    environment: 
      - cluster.name=lumisportal
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "action.auto_create_index= -lumisportal-*,+*"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - lumis-analysis:/usr/share/elasticsearch/config/lumis-analysis
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - lumis
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  lumisportal:
    #build: ./lumisportal
    image: jeduoliveira/lumisportal-stack:11.2.0.190404        
    environment:
      TOMCAT_AJP_MAX_THREADS: 50
      TOMCAT_HTTP_MAX_THREADS: 10
      TOMCAT_HEAP: 1G
      LUMIS_DB_HOST: db
      LUMIS_DB_PORT: 3306
      LUMIS_DB_USER: lumisportal
      LUMIS_DB_PASSWORD: lumisportal
      LUMIS_DB_NAME: lumisportal
      LUMIS_DB_MINIMUM_IDLE: 10
      LUMIS_DB_MAXIMUM_POOL_SIZE: 100
      LUMIS_SERVER_ID: Server1
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_CLUSTER_NAME: lumisportal      
    volumes: 
      - lumis-analysis:/usr/share/elasticsearch/config/lumis-analysis
      - lumis_data:/usr/local/lumisportal/lumisdata/data
      - lumis_shared:/usr/local/lumisportal/lumisdata/shared
      - lumis_htdocs:/usr/local/htdocs
    depends_on:
       - db
    links:
      - db
      - elasticsearch
    networks:
      - lumis
    ports:
      - 8080:8080
    healthcheck:
      test: curl -sS http://localhost:8080/login.jsp || exit 1
      interval: 60s
      timeout: 10s
      retries: 50
        
  apache:
    #build: ./httpd
    image: jeduoliveira/lumisportal-stack-httpd        
    depends_on: 
      - lumisportal
    links:
      - lumisportal
    volumes: 
      - lumis_htdocs:/usr/local/htdocs
    networks: 
      - lumis
    ports:
      - 80:80
    
networks: {lumis: {}}

volumes:
  mysql-data:
  elastic-data:
  lumis-analysis:
  lumis_data:
  lumis_shared: 
  lumis_htdocs: